### ISSUE TITLE
Versão do Delphi no readme

### ISSUE THREAD

**Issue by josircg** [Daniel09Fernandes/Component_OpenOffice_Calc#2]
Opa Daniel. Seria importante você indicar que essa rotina funciona no Delphi. E para quais versões do Delphi ela funciona.

**Comment by Daniel09Fernandes** [comment]
Opa, boa tarde Josir, perfeito, melhorei o readme, com as versões do Delphi em que testei, e uma anotação de units adicional para o uso do componente, que julguei importante.

Obrigado pela mensagem.

Att
Daniel Fernandes
